# Change these first
owner: sahajananddigital # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Sahajananad Digital
    url: https://sahajananddigital.in
  - name: Aquapex Ro
    url: https://aquapexro.in
  - name: Sahajanand Projects
    url: https://projects.sahajananddigital.in
  - name: Vedik Gurukulam
    url: https://vedikgurukulam.org
  - name: Sidhhatva Accountants LLP
    url: https://siddhatvaaccountants.com
  - name: Shrihari Charitra
    url: https://shriharicharitra.com
  - name: Harikrusna International
    url: https://shreeharikrushnaintl.com
  - name: LeosonPharma.com ( WalArt Pharma )
    url: https://leosonpharma.com
  - name: megmahealth.com ( WalArt Pharma )
    url: https://megmahealth.com
  - name: RelyCore Solutions
    url: https://relycoresolutions.com
  - name: Prevail Engineering
    url: https://prevailengg.com
  - name: Prasham Industries
    url: https://prashamindustries.com
  - name: Shiksha Skills Institute
    url: http://shikshaskills.org.in
  - name: Saurya Technology
    url: https://sauryatechnology.com
  - name: AksharLife Science # server1.sahajananddigital.in
    url: https://www.aksharlifescience.com
    
assignees: # Users to assign downtime issues (optional)
  - vanpariyar

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.sahajananddigital.in
  # baseUrl: ./status
  logoUrl: https://sahajananddigital.in/images/logo.png
  name: Sahajanand digital web status moniter by Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
